### ISSUE TITLE
haste_pytorch does not install properly with conda cudatoolkit?

### ISSUE THREAD

**Issue by Harimus** [lmnt-com/haste#41]
Hi, So I've been trying to install haste on my 3 machines with only one successful. (One of them installed, but `Segmentation fault` as soon as I throw tensors to GPU to be used with haste, the other one just errors out at some g++ compiler step in wheel)

So I've tried to move to docker, with [repo2docker](https://repo2docker.readthedocs.io/en/latest/) to make the process easier for my coworkers. However the image build still crashes at `haste-pytorch` build stage, while using `conda` for build process. As the [haste pypi](https://pypi.org/project/haste-pytorch/) documentation state cuda toolkit 10.1+ is required, I assumed conda provided cuda toolkit sufficed, but seems like in the build-from-scratch process, this is not the case?

If I'm doing something wrong/misinterpreting, feedback would be more than welcome!

**Comment by sharvil** [comment]
My best guess is that your installed PyTorch isn't using the same CUDA toolkit as Haste. When a prebuilt PyTorch is installed (e.g. via pip or conda), it uses its own copy of CUDA Toolkit instead of what's installed on your system. Haste, on the other hand, uses the CUDA toolkit found in `/usr/local/cuda`. I've seen segfaults with Haste + PyTorch when I had CUDA version mismatches.

Conda doesn't install the CUDA toolkit to `/usr/local/cuda` so you'll need to edit Haste's `Makefile` to point to the right place.

**Comment by Harimus** [comment]
Hi Thanks for the answer!
As for the Segfault message, When I changed the Cuda from 11.4 to 11.1 (in `PATH` ) and downloaded and built it from the source, rather than with `pip`, it worked. (It did not work with pip nor source with 11.4. Maybe I should've collected the build error msg. my bad)

As for the other question, thank you for the clarification. seems like the repo2docker uses old (<10.1 ) cuda toolkit by default and installing it by changing the base docker image to `devel` version of nvidia/ubuntu that contains all the necessary build tools is not possible, so I'll go with another option on that one. 

Thanks again!

**Comment by sharvil** [comment]
No problem, glad you got up and running at least locally. Let me know if you run into any other issues that I can help with.
